import { defineId, type RecipeId } from './ids'
import {
  BROWN_SUGAR,
  BUTTER,
  CHOCOLATE_CHIPS,
  CINNAMON,
  COCOA,
  COCONUT,
  EGG,
  FLOUR,
  HONEY,
  LEMON,
  MAPLE_SYRUP,
  OATS,
  PEANUT_BUTTER,
  PISTACHIO,
  SEA_SALT,
  STRAWBERRY_JAM,
  SUGAR,
  VANILLA,
  WHITE_CHOCOLATE,
} from './ingredients'
import type { Recipe } from './types'

/**
 * The recipe catalog. Each recipe is an exact set of ingredients; the order
 * they went into the bowl never matters. Every set must be unique, which the
 * catalog checks (domain/catalog) enforce.
 *
 * Never reuse or rename an id once shipped; saves record discoveries by id.
 *
 * Rarity is part of the recipe, fixed here: it never changes between bakes.
 * Keep it mostly grounded. Starter recipes are common; a recipe earns a
 * higher rarity by being genuinely unusual to find (no flour, two kinds of
 * chocolate, ingredients that only arrive late).
 *
 * Family, rarity and secrecy are separate choices. A secret can be any
 * rarity from Rare up, and it belongs to an ordinary family like any other
 * recipe; it just has no card and no clue until it's baked.
 *
 * Clues are Marmalade's scribbles for undiscovered cards: a feeling, a
 * texture, a time of day. Never an ingredient's name.
 */

export const RECIPES: readonly Recipe[] = [
  {
    id: defineId('recipe', 'shortbread'),
    name: 'Shortbread',
    ingredientIds: [FLOUR, SUGAR, BUTTER],
    description: 'Three ingredients, pressed flat and cut into squares. Snaps cleanly and melts on the tongue.',
    descriptors: ['buttery', 'crumbly', 'plain in the best way'],
    look: { dough: 'pale', topping: 'none', shape: 'square' },
    discoveryText: 'The oldest trick in the tin: flour, sugar, butter.',
    rarity: 'common',
    family: 'classics',
    isSecret: false,
    clue: 'Plain in the best way. Just the basics.',
  },
  {
    id: defineId('recipe', 'sugar-cookie'),
    name: 'Sugar Cookie',
    ingredientIds: [FLOUR, SUGAR, BUTTER, EGG],
    description: 'Soft in the middle, golden at the edge, with a sparkle of sugar on top.',
    descriptors: ['soft', 'sweet', 'golden'],
    look: { dough: 'golden', topping: 'sugar', shape: 'round' },
    discoveryText: 'An egg made all the difference. A proper cookie.',
    rarity: 'common',
    family: 'classics',
    isSecret: false,
    clue: 'Soft in the middle and golden at the edge.',
  },
  {
    id: defineId('recipe', 'vanilla-kiss'),
    name: 'Vanilla Kiss',
    ingredientIds: [FLOUR, SUGAR, BUTTER, EGG, VANILLA],
    description: 'A pale, tender little cookie that smells of vanilla long after it has cooled.',
    descriptors: ['tender', 'fragrant', 'delicate'],
    look: { dough: 'pale', topping: 'vanilla-flecks', shape: 'round' },
    discoveryText: 'Just a few drops, and the whole kitchen smells of it.',
    rarity: 'uncommon',
    family: 'classics',
    isSecret: false,
    clue: 'Smells like a warm kitchen long after it cools.',
  },
  {
    id: defineId('recipe', 'chocolate-chip'),
    name: 'Chocolate Chip Cookie',
    ingredientIds: [FLOUR, SUGAR, BUTTER, EGG, CHOCOLATE_CHIPS],
    description: 'Chewy, golden and dotted with pools of melted chocolate.',
    descriptors: ['chewy', 'melty', 'classic'],
    look: { dough: 'golden', topping: 'chips', shape: 'round' },
    discoveryText: 'Everyone’s favourite. Worth writing down.',
    rarity: 'common',
    family: 'chocolate',
    isSecret: false,
    clue: 'Everyone’s favourite. You know the one.',
  },
  {
    id: defineId('recipe', 'snickerdoodle'),
    name: 'Snickerdoodle',
    ingredientIds: [FLOUR, SUGAR, BUTTER, EGG, CINNAMON],
    description: 'Crackly-topped and rolled in cinnamon sugar. Soft, warm and a bit tangy.',
    descriptors: ['crackly', 'warm', 'cinnamony'],
    look: { dough: 'spiced', topping: 'cinnamon-sugar', shape: 'round' },
    discoveryText: 'A silly name for a very serious cookie.',
    rarity: 'uncommon',
    family: 'warm-spiced',
    isSecret: false,
    clue: 'Something warm and spiced, with a silly name.',
  },
  {
    id: defineId('recipe', 'cocoa-crinkle'),
    name: 'Cocoa Crinkle',
    ingredientIds: [FLOUR, SUGAR, BUTTER, EGG, COCOA],
    description: 'Dark and fudgy, with a surface that cracks open as it bakes.',
    descriptors: ['fudgy', 'cracked', 'deep'],
    look: { dough: 'cocoa', topping: 'crinkle', shape: 'round' },
    discoveryText: 'It split open in the oven, and that’s exactly right.',
    rarity: 'uncommon',
    family: 'chocolate',
    isSecret: false,
    clue: 'Dark and fudgy, and it cracks open in the oven.',
  },
  {
    id: defineId('recipe', 'double-chocolate'),
    name: 'Double Chocolate Shortbread',
    ingredientIds: [FLOUR, SUGAR, BUTTER, COCOA, CHOCOLATE_CHIPS],
    description: 'Shortbread gone dark: cocoa in the dough and chocolate chips pressed on top.',
    descriptors: ['rich', 'snappy', 'very chocolatey'],
    look: { dough: 'dark', topping: 'chips', shape: 'square' },
    discoveryText: 'No egg, twice the chocolate. Dangerous.',
    rarity: 'epic',
    family: 'chocolate',
    isSecret: false,
    clue: 'Twice as dark, and crisp rather than chewy.',
  },
  // ---- Interval 3 ----
  {
    id: defineId('recipe', 'oatmeal-cookie'),
    name: 'Oatmeal Cookie',
    ingredientIds: [FLOUR, SUGAR, BUTTER, EGG, OATS],
    description: 'Chewy and rough-edged, with oats you can see and a middle that stays soft for days.',
    descriptors: ['chewy', 'hearty', 'wholesome'],
    look: { dough: 'golden', topping: 'oats', shape: 'round' },
    discoveryText: 'A handful of oats turned a cookie into breakfast. Almost.',
    rarity: 'common',
    family: 'classics',
    isSecret: false,
    clue: 'Hearty enough to call breakfast. Almost.',
  },
  {
    id: defineId('recipe', 'peanut-butter-cookie'),
    name: 'Peanut Butter Cookie',
    ingredientIds: [PEANUT_BUTTER, SUGAR, EGG],
    description: 'No flour at all. Soft, sandy and pressed flat with a fork, the way it always has been.',
    descriptors: ['nutty', 'sandy', 'fork-pressed'],
    look: { dough: 'nutty', topping: 'fork-marks', shape: 'round' },
    discoveryText: 'Three things and a fork. Who needs flour?',
    rarity: 'rare',
    family: 'nutty',
    isSecret: false,
    clue: 'Rich and sandy, and pressed flat with a fork.',
  },
  {
    id: defineId('recipe', 'peanut-butter-chocolate'),
    name: 'Peanut Butter Chocolate Chip',
    ingredientIds: [PEANUT_BUTTER, SUGAR, EGG, CHOCOLATE_CHIPS],
    description: 'The flourless peanut butter cookie, studded with chocolate that goes soft in the heat.',
    descriptors: ['nutty', 'melty', 'rich'],
    look: { dough: 'nutty', topping: 'chips', shape: 'round' },
    discoveryText: 'Peanut butter and chocolate. Of course they belong together.',
    rarity: 'epic',
    family: 'nutty',
    isSecret: false,
    clue: 'Two things that were always meant to meet.',
  },
  {
    id: defineId('recipe', 'honey-flapjack'),
    name: 'Honey Flapjack',
    ingredientIds: [OATS, BUTTER, HONEY],
    description: 'Oats pressed into a tin with melted butter and honey, baked golden and cut into bars.',
    descriptors: ['sticky', 'golden', 'chewy'],
    look: { dough: 'golden', topping: 'oats', shape: 'square' },
    discoveryText: 'Sticky fingers, and worth it.',
    rarity: 'legendary',
    family: 'sweet-sticky',
    isSecret: false,
    clue: 'Sticky, golden, and cut into bars.',
  },
  {
    id: defineId('recipe', 'coconut-macaroon'),
    name: 'Coconut Macaroon',
    ingredientIds: [COCONUT, SUGAR, EGG],
    description: 'Little mounds of coconut, crisp and toasted outside, soft and sweet within.',
    descriptors: ['toasty', 'chewy', 'sweet'],
    look: { dough: 'pale', topping: 'coconut', shape: 'round' },
    discoveryText: 'Egg and sugar held the coconut together, just.',
    rarity: 'rare',
    family: 'curious',
    isSecret: false,
    clue: 'Toasty little mounds that barely hold together.',
  },
  // ---- Interval 6 ----
  {
    id: defineId('recipe', 'meringue-kiss'),
    name: 'Meringue Kiss',
    ingredientIds: [EGG, SUGAR],
    description: 'Whipped until it stands in peaks, piped into little kisses and dried slowly until they rattle.',
    descriptors: ['airy', 'crisp', 'melting'],
    look: { dough: 'snow', topping: 'swirl', shape: 'round' },
    discoveryText: 'Two things, and it turned into a cloud.',
    rarity: 'uncommon',
    family: 'curious',
    isSecret: false,
    clue: 'Light as a cloud. Hardly anything to it.',
  },
  {
    id: defineId('recipe', 'jam-thumbprint'),
    name: 'Jam Thumbprint',
    ingredientIds: [FLOUR, SUGAR, BUTTER, STRAWBERRY_JAM],
    description: 'A soft round of shortbread with a thumb pressed into the middle and filled with glossy jam.',
    descriptors: ['tender', 'glossy', 'fruity'],
    look: { dough: 'golden', topping: 'jam-dot', shape: 'round' },
    discoveryText: 'Press, fill, bake. A little jewel on every one.',
    rarity: 'common',
    family: 'fruity',
    isSecret: false,
    clue: 'Press a thumb in the middle and fill it with something bright.',
  },
  {
    id: defineId('recipe', 'lemon-shortbread'),
    name: 'Lemon Shortbread',
    ingredientIds: [FLOUR, SUGAR, BUTTER, LEMON],
    description: 'Shortbread with zest rubbed into the sugar, so every bite tastes of sunshine.',
    descriptors: ['zesty', 'buttery', 'snappy'],
    look: { dough: 'pale', topping: 'zest', shape: 'square' },
    discoveryText: 'The kitchen suddenly smells like summer.',
    rarity: 'common',
    family: 'fruity',
    isSecret: false,
    clue: 'Sunny and sharp, and very simple.',
  },
  {
    id: defineId('recipe', 'blondie'),
    name: 'Blondie',
    ingredientIds: [FLOUR, BROWN_SUGAR, BUTTER, EGG],
    description: 'Fudgy, chewy squares that taste of toffee and butterscotch, with a crackly top.',
    descriptors: ['fudgy', 'toffee-ish', 'chewy'],
    look: { dough: 'caramel', topping: 'none', shape: 'square' },
    discoveryText: 'Like a brownie, if a brownie had never met chocolate.',
    rarity: 'common',
    family: 'classics',
    isSecret: false,
    clue: 'A brownie that never went dark.',
  },
  {
    id: defineId('recipe', 'honeycomb'),
    name: 'Honeycomb Crunch',
    ingredientIds: [SUGAR, HONEY],
    description: 'Bubbled up in the pan and set into golden, glassy shards that shatter when you bite.',
    descriptors: ['crunchy', 'golden', 'bubbly'],
    look: { dough: 'caramel', topping: 'bubbles', shape: 'square' },
    discoveryText: 'It foamed up like magic and set like glass.',
    rarity: 'common',
    family: 'sweet-sticky',
    isSecret: false,
    clue: 'Golden and crackly. Not really a biscuit at all.',
  },
  {
    id: defineId('recipe', 'lemon-crinkle'),
    name: 'Lemon Crinkle',
    ingredientIds: [FLOUR, SUGAR, BUTTER, EGG, LEMON],
    description: 'Soft and bright, rolled in sugar so the top crackles into a crazy-paving pattern.',
    descriptors: ['bright', 'soft', 'crackly'],
    look: { dough: 'lemon', topping: 'crinkle', shape: 'round' },
    discoveryText: 'Sharp, sweet and cracked all over. Lovely.',
    rarity: 'uncommon',
    family: 'fruity',
    isSecret: false,
    clue: 'Bright and sharp, and it cracks as it bakes.',
  },
  {
    id: defineId('recipe', 'maple-cinnamon-snap'),
    name: 'Maple Cinnamon Snap',
    ingredientIds: [FLOUR, BROWN_SUGAR, BUTTER, CINNAMON, MAPLE_SYRUP],
    description: 'Thin, crisp and deeply spiced, with a drizzle of maple glaze across the top.',
    descriptors: ['crisp', 'spiced', 'glazed'],
    look: { dough: 'spiced', topping: 'drizzle', shape: 'round' },
    discoveryText: 'It snaps clean in half and smells like a bonfire night.',
    rarity: 'uncommon',
    family: 'warm-spiced',
    isSecret: false,
    clue: 'Autumn leaves, in biscuit form.',
  },
  {
    id: defineId('recipe', 'pancake-cookie'),
    name: 'Pancake Cookie',
    ingredientIds: [FLOUR, BUTTER, EGG, MAPLE_SYRUP],
    description: 'No sugar at all: just maple, so it tastes exactly like a stack of pancakes.',
    descriptors: ['soft', 'buttery', 'breakfast-y'],
    look: { dough: 'golden', topping: 'drizzle', shape: 'round' },
    discoveryText: 'Wait. This is breakfast. You’ve baked breakfast.',
    rarity: 'uncommon',
    family: 'curious',
    isSecret: false,
    clue: 'Tastes like a slow Sunday morning.',
  },
  {
    id: defineId('recipe', 'white-chocolate-snowdrop'),
    name: 'White Chocolate Snowdrop',
    ingredientIds: [FLOUR, SUGAR, BUTTER, VANILLA, WHITE_CHOCOLATE],
    description: 'Pale, fragrant shortbread rounds studded with creamy white chocolate.',
    descriptors: ['creamy', 'fragrant', 'pale'],
    look: { dough: 'pale', topping: 'white-chips', shape: 'round' },
    discoveryText: 'Pale as a snowdrop and twice as sweet.',
    rarity: 'rare',
    family: 'chocolate',
    isSecret: false,
    clue: 'Pale as snow, and sweeter than it looks.',
  },
  {
    id: defineId('recipe', 'pistachio-biscotti'),
    name: 'Pistachio Biscotti',
    ingredientIds: [FLOUR, SUGAR, EGG, PISTACHIO],
    description: 'Baked once as a log, sliced, then baked again until crisp. No butter, all crunch.',
    descriptors: ['crunchy', 'nutty', 'twice-baked'],
    look: { dough: 'pale', topping: 'pistachio', shape: 'square' },
    discoveryText: 'Baked twice and made for dunking.',
    rarity: 'rare',
    family: 'nutty',
    isSecret: false,
    clue: 'Baked twice, and made for dunking.',
  },
  {
    id: defineId('recipe', 'salted-butterscotch'),
    name: 'Salted Butterscotch',
    ingredientIds: [BROWN_SUGAR, BUTTER, SEA_SALT],
    description: 'Brown sugar and butter cooked to a deep amber, poured into drops and finished with salt.',
    descriptors: ['toffee-ish', 'salty-sweet', 'melting'],
    look: { dough: 'caramel', topping: 'salt-flakes', shape: 'round' },
    discoveryText: 'Just a pinch of salt, and suddenly it’s grown up.',
    rarity: 'rare',
    family: 'sweet-sticky',
    isSecret: false,
    clue: 'Sweet, but not too sweet. Melts like toffee.',
  },
  {
    id: defineId('recipe', 'millionaires-shortbread'),
    name: 'Millionaire’s Shortbread',
    ingredientIds: [FLOUR, BUTTER, BROWN_SUGAR, SEA_SALT, CHOCOLATE_CHIPS],
    description:
      'A crisp shortbread base, a thick layer of salted caramel, and dark chocolate set over the top. Cut into very small squares, because it is very rich.',
    descriptors: ['layered', 'salted caramel', 'decadent'],
    look: { dough: 'dark', topping: 'salt-flakes', shape: 'square' },
    discoveryText: 'Three layers, every one of them perfect. This one’s worth a fortune.',
    rarity: 'mythic',
    family: 'sweet-sticky',
    isSecret: false,
    clue: 'Three layers, and the middle one is salty-sweet. Worth a fortune.',
  },
  // ---- Interval 8: aimed at the ingredients that had only one card to their name
  // (coconut, jam, white chocolate, pistachios) and at the thinnest dividers. ----
  {
    id: defineId('recipe', 'chocolate-haystack'),
    name: 'Chocolate Haystack',
    ingredientIds: [COCONUT, CHOCOLATE_CHIPS, OATS],
    description: 'Rough little heaps of coconut and oats, stirred through melted chocolate and left on the side to set.',
    descriptors: ['no-bake', 'chewy', 'rough-edged'],
    look: { dough: 'cocoa', topping: 'coconut', shape: 'round' },
    discoveryText: 'The oven never even came on. It still counts.',
    rarity: 'uncommon',
    family: 'curious',
    isSecret: false,
    clue: 'Never goes near the oven. Looks like a heap of hay.',
  },
  {
    id: defineId('recipe', 'jam-sandwich'),
    name: 'Jam Sandwich',
    ingredientIds: [FLOUR, SUGAR, BUTTER, VANILLA, STRAWBERRY_JAM],
    description: 'Two crisp, fragrant rounds with jam spread between, and a little window cut in the top to show it off.',
    descriptors: ['crisp', 'jammy', 'sandwiched'],
    look: { dough: 'pale', topping: 'jam-dot', shape: 'round' },
    discoveryText: 'Two biscuits are better than one, if there’s something in the middle.',
    rarity: 'uncommon',
    family: 'fruity',
    isSecret: false,
    clue: 'Two of them, stuck together with something bright.',
  },
  {
    id: defineId('recipe', 'lemon-white-chocolate'),
    name: 'Lemon White Chocolate Cookie',
    ingredientIds: [FLOUR, SUGAR, BUTTER, LEMON, WHITE_CHOCOLATE],
    description: 'A sharp, sunny dough with pools of white chocolate through it, so every bite is sour, then sweet.',
    descriptors: ['zesty', 'creamy', 'soft-centred'],
    look: { dough: 'lemon', topping: 'white-chips', shape: 'round' },
    discoveryText: 'Sour and sweet, taking turns. Nobody wins, and everybody does.',
    rarity: 'rare',
    family: 'fruity',
    isSecret: false,
    clue: 'Sour and sweet, taking turns in every bite.',
  },
  {
    id: defineId('recipe', 'pistachio-nougat'),
    name: 'Pistachio Nougat',
    ingredientIds: [EGG, SUGAR, HONEY, PISTACHIO],
    description: 'Egg whites whisked into hot honey and sugar until thick and glossy, then set with green pistachios all through it.',
    descriptors: ['chewy', 'honeyed', 'studded'],
    look: { dough: 'snow', topping: 'pistachio', shape: 'square' },
    discoveryText: 'Sticky, glossy and nothing like a biscuit. Worth every minute of whisking.',
    rarity: 'epic',
    family: 'nutty',
    isSecret: false,
    clue: 'Pale and chewy, freckled with green, and nothing like a biscuit.',
  },
  {
    id: defineId('recipe', 'cinnamon-bun-cookie'),
    name: 'Cinnamon Bun Cookie',
    ingredientIds: [FLOUR, BROWN_SUGAR, BUTTER, EGG, CINNAMON],
    description: 'Soft and chewy, with dark sugar and spice rolled through it like the middle of a bun.',
    descriptors: ['soft', 'swirly', 'warm'],
    look: { dough: 'caramel', topping: 'cinnamon-sugar', shape: 'round' },
    discoveryText: 'It smells exactly like a bakery window on a cold morning.',
    rarity: 'common',
    family: 'warm-spiced',
    isSecret: false,
    clue: 'Like the middle of a sticky bun, on a cold morning.',
  },
  {
    id: defineId('recipe', 'spiced-cocoa-square'),
    name: 'Spiced Cocoa Square',
    ingredientIds: [FLOUR, SUGAR, BUTTER, COCOA, CINNAMON],
    description: 'Dark, crisp shortbread with a warm kick of spice, cut into squares and dusted with sugar.',
    descriptors: ['dark', 'spiced', 'snappy'],
    look: { dough: 'cocoa', topping: 'sugar', shape: 'square' },
    discoveryText: 'Like a mug of something hot and spiced, if you could snap it in half.',
    rarity: 'common',
    family: 'warm-spiced',
    isSecret: false,
    clue: 'A warm drink on a cold night, only crisp.',
  },
  // Honey costs a lot of Crumbs, and until now it made only one thing from the
  // starter shelf. With the extra XP above, a kitchen could buy it early and be
  // left with too little to add anything else; a second honey card from the
  // basics keeps that from ever being a dead end (progression.test checks).
  {
    id: defineId('recipe', 'honey-madeleine'),
    name: 'Honey Madeleine',
    ingredientIds: [FLOUR, SUGAR, BUTTER, EGG, HONEY],
    description: 'Little shell-shaped sponges with a hump on top, golden at the edges and fragrant with honey.',
    descriptors: ['spongy', 'golden', 'honeyed'],
    look: { dough: 'golden', topping: 'drizzle', shape: 'round' },
    discoveryText: 'They rose in the middle, like little hills. That hump is the whole point.',
    rarity: 'common',
    family: 'sweet-sticky',
    isSecret: false,
    clue: 'Shaped like a seashell, with a little hump in the middle.',
  },
  // ---- Interval 6 secrets: no card, count or clue until they're baked ----
  {
    id: defineId('recipe', 'snowball'),
    name: 'Snowball',
    ingredientIds: [COCONUT, SUGAR, EGG, WHITE_CHOCOLATE],
    description: 'A coconut macaroon with a heart of white chocolate, rolled until it looks like a snowball.',
    descriptors: ['snowy', 'chewy', 'creamy'],
    look: { dough: 'snow', topping: 'coconut', shape: 'round' },
    discoveryText: 'It looks like it fell out of a winter sky.',
    rarity: 'rare',
    family: 'curious',
    isSecret: true,
    clue: null,
  },
  {
    id: defineId('recipe', 'peanut-butter-jam'),
    name: 'Peanut Butter & Jam Thumbprint',
    ingredientIds: [PEANUT_BUTTER, SUGAR, EGG, STRAWBERRY_JAM],
    description: 'The flourless peanut butter cookie with a pool of strawberry jam in the middle. A lunchbox in a bite.',
    descriptors: ['nutty', 'jammy', 'nostalgic'],
    look: { dough: 'nutty', topping: 'jam-dot', shape: 'round' },
    discoveryText: 'Somebody’s school lunch, turned into a cookie.',
    rarity: 'epic',
    family: 'nutty',
    isSecret: true,
    clue: null,
  },
  {
    id: defineId('recipe', 'baklava-bite'),
    name: 'Baklava Bite',
    ingredientIds: [FLOUR, BUTTER, PISTACHIO, HONEY, CINNAMON],
    description: 'Paper-thin layers brushed with butter, packed with spiced pistachios and soaked in honey.',
    descriptors: ['flaky', 'honeyed', 'spiced'],
    look: { dough: 'golden', topping: 'pistachio', shape: 'square' },
    discoveryText: 'Layer on layer on layer. Nobody told you about this one.',
    rarity: 'legendary',
    family: 'warm-spiced',
    isSecret: true,
    clue: null,
  },
]

const byId = new Map(RECIPES.map((recipe) => [recipe.id, recipe]))

export function findRecipeById(id: RecipeId): Recipe | undefined {
  return byId.get(id)
}
